language: python

python:
    - 3.5

install:
    - pip install coveralls
    - python setup.py install

services:
    - redis-server

script:
    - coverage run --source=news setup.py test

after_success:
    - coveralls
