COVER_PUSHER_CYCLE = 5
REDIS_PUBSUB_SLEEP_TIME = 0.001
REDIS_SCHEDULE_CREATE_CHANNEL = 'NEWS_SCHEDULE_CREATED'
REDIS_SCHEDULE_UPDATE_CHANNEL = 'NEWS_SCHEDULE_UPDATED'
REDIS_SCHEDULE_DELETE_CHANNEL = 'NEWS_SCHEDULE_DELETED'

DEFAULT_SCHEDULE_CYCLE = 300
DEFAULT_MAX_VISIT = 200
DEFAULT_MAX_DIST = None
DEFAULT_MAX_DEPTH = None
DEFAULT_BLACKLIST = ['png', 'jpg', 'gif', 'pdf', 'svg', 'zip']
DEFAULT_BROTHERS = []
